Feature/extend faq
kiboko-labs/docker-images pull request #18
Opened 2020-12-15 14:24 UTC by sebprt

- Ajout de la FAQ en français et de quelques questions
- Modification doc usage suite à la version 1.2

2020-12-15 14:33 UTC, XaBe20 approved these changes

2020-12-15 15:39 UTC, gplanchat requested changes

2020-12-15 15:39 UTC, gplanchat commented on README.md
> +* [Frequently Asked Questions FR](docs/faq_fr.md)
Ne mets pas les liens en français pour l'instant, on mettra en place hugo par la suite

2020-12-15 15:39 UTC, gplanchat commented on docs/faq_en.md
> +</details>
Non, c'est dans le cas où le package Phar n'a pas été placé sur la release Github. C'est à nous de gérer, pas à l'utilisateur.

2020-12-15 15:39 UTC, gplanchat commented on docs/faq_en.md
> +        - 'YOUR_PORT:1025'
Je ne comprend pas ce qu'on cherche à résoudre ici.
D'autre part, on devrait utiliser une variable d'environnement `${SMTP_PORT}`

2020-12-15 15:39 UTC, gplanchat commented on docs/usage.md
> +> Initialize the Docker stack in a project without Docker stack
Il y a un erreur dans la description de la commande

2020-12-16 09:24 UTC, sebprt commented on README.md
> +* [Frequently Asked Questions FR](docs/faq_fr.md)
Corrigé : https://github.com/kiboko-labs/kloud/pull/18/commits/18f6a075d1952eea29406a078cc274be098b6634

2020-12-16 09:25 UTC, sebprt commented on docs/faq_en.md
> +</details>
Point supprimé https://github.com/kiboko-labs/kloud/pull/18/commits/18f6a075d1952eea29406a078cc274be098b6634

2020-12-18 09:52 UTC, sebprt commented on docs/usage.md
> +> Initialize the Docker stack in a project without Docker stack
Description changée

2020-12-18 09:53 UTC, sebprt commented on docs/faq_en.md
> +        - 'YOUR_PORT:1025'
Point supprimé

2020-12-18 09:55 UTC, gplanchat approved these changes

2020-12-18 09:55 UTC, merged